version: "3.8"

services:
  php:
    build:
        context: ./docker/php
        dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony
    user: 1000:1001
    environment:
      - "APACHE_DOCUMENT_ROOT=/var/www/html/public"

networks:
  symfony:
